services:
  processor-dev:
    build: 
      dockerfile: Dockerfile.dev
    environment:
      - OLLAMA_URL=http://172.16.100.181:8080
      - WORKER_URL=https://apatin.ru
      - HEALTH_ADDR=0.0.0.0:8081
      - POLLING_ENABLED=false
      - POLL_INTERVAL=300s
      - MAX_RETRIES=5
      - REQUEST_TIMEOUT=30s
      - MODEL_NAME=gemma3:1b
      - WORKER_COUNT=2
      - QUEUE_SIZE=8
      - MAX_BATCH_SIZE=8
      - PROCESSOR_ID=iMac15
      - HEARTBEAT_INTERVAL=10s
      - INTERNAL_API_KEY=HiVfodusmowitvejeggaquztobaq43
      - SSE_ENABLED=true
      - SSE_ENDPOINT=/api/internal/task-stream
      - SSE_RECONNECT_INTERVAL=3s
      - SSE_MAX_RECONNECT_ATTEMPTS=1000000
      - SSE_HEARTBEAT_TIMEOUT=60s
    networks:
      - llm-proxy-network

networks:
  llm-proxy-network:
    driver: bridge
