services:
  processor-dev:
    build: 
      dockerfile: Dockerfile.dev
    environment:
      - OLLAMA_URL=http://host.docker.internal:11434
      - WORKER_URL=http://host.docker.internal:8080
      - HEALTH_ADDR=0.0.0.0:8081
      - POLL_INTERVAL=1s
      - MAX_RETRIES=3
      - REQUEST_TIMEOUT=30s
      - MODEL_NAME=gemma3:1b
      - WORKER_COUNT=2
      - QUEUE_SIZE=100
      - MAX_BATCH_SIZE=8
      - PROCESSOR_ID=iMac15
      - HEARTBEAT_INTERVAL=10s
      - INTERNAL_API_KEY=dev-internal-key
      - SSE_ENABLED=true
      - SSE_ENDPOINT=/api/internal/task-stream
      - SSE_RECONNECT_INTERVAL=30s
      - SSE_MAX_RECONNECT_ATTEMPTS=1000000
      - SSE_HEARTBEAT_TIMEOUT=60s
    networks:
      - llm-proxy-network

networks:
  llm-proxy-network:
    driver: bridge
