services:
  processor-dev:
    build: 
      dockerfile: Dockerfile.dev
    environment:
      - OLLAMA_URL=http://host.docker.internal:11434
      - WORKER_URL=http://host.docker.internal:8080
      - HEALTH_ADDR=0.0.0.0:8081
      - POLLING_ENABLED=true
      - POLL_INTERVAL=300s
      - MAX_RETRIES=5
      - REQUEST_TIMEOUT=300s
      - MODEL_NAME=gemma3:1b
      - WORKER_COUNT=1
      - QUEUE_SIZE=8
      - MAX_BATCH_SIZE=8
      - PROCESSOR_ID=dev
      - HEARTBEAT_INTERVAL=10s
      - INTERNAL_API_KEY=dev-internal-key
      - SSE_ENABLED=false
      - SSE_ENDPOINT=/api/internal/task-stream
      - SSE_RECONNECT_INTERVAL=3s
      - SSE_MAX_RECONNECT_ATTEMPTS=1000000
      - SSE_HEARTBEAT_TIMEOUT=60s
      - SSE_MAX_DURATION=3600s
    networks:
      - llm-proxy-network

networks:
  llm-proxy-network:
    driver: bridge
